# Generated by Django 5.2.4 on 2025-08-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'TO DO'), ('in_progress', 'IN PROGRESS'), ('complete', 'COMPLETE')], max_length=20)),
                ('priority', models.CharField(choices=[('low_priority', 'LOW PRIORITY'), ('middle_priority', 'MIDDLE PRIORITY'), ('high_priority', 'HIGH PRIORITY')], max_length=20)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
